### ISSUE TITLE
Move into the alexa-js organization?

### ISSUE THREAD

**Issue by dblock** [alexa-js/alexa-verifier#10]
Would you like to move this repo into the newly created alexa-js organization, https://github.com/alexa-js? 

This would reduce bus factor as currently only @mreinstein can add contributors to this project. By moving org admins can at least add new people, currently that's @matt-kruse and myself.

If you do want to do this, because Github requires one be admin of both source and destination, transfer the repo to me (@dblock) and I'll immediately move it to the org.

**Comment by mreinstein** [comment]
see https://github.com/mreinstein/alexa-utterances/issues/18

**Comment by dblock** [comment]
Consider adding me and/or @matt-kruse to npm as well, please.

**Comment by mreinstein** [comment]
done
