### ISSUE TITLE
Caching certificates to /tmp opens up a security problem?

### ISSUE THREAD

**Issue by martijnthe** [alexa-js/alexa-verifier#5]
See https://github.com/mreinstein/alexa-verifier/blob/master/index.js#L29

Isn't this opening up a security problem? The file could be (over)written by another program, for example to replace it with another certificate.

To be on the safe side, I would just avoid caching it on disk, but just keep an in-memory cache. 

Thoughts?

**Comment by mreinstein** [comment]
> Isn't this opening up a security problem?

I guess it depends on your usage. These days, most web services are hosted on virtual servers. Shared user environments aren't as common in my opinion.

> To be on the safe side, I would just avoid caching it on disk, but just keep an in-memory cache.

I'm certainly not opposed to accepting a PR, as long as it doesn't add complexity to the module.

**Comment by martijnthe** [comment]
Opened a PR to improve this.
I think it actually simplifies the code rather than complicating it :)

**Comment by mreinstein** [comment]
thanks :) See the PR for my comments.

**Comment by mreinstein** [comment]
fixed via https://github.com/alexa-js/alexa-verifier/commit/e0716135cbeb0eafdf7180b62f34db0c9cbe0af9
